name: Deploy on Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_NAME: todo-api

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: bluebuilder/azure:latest
    steps:
      - name: Check setup
        run: |
          if [ -z "${AZURE_CREDENTIALS}" ]; then
            echo "Azure credentials not found."
            echo "Please run .azure/setup.sh to setup your deployment."
            exit 1
          fi
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd api && npm ci
        env:
          CI: true
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create infrastructure
        run: cd .azure && ./infra.sh up ${{ env.PROJECT_NAME }}
      - name: Deploy project
        run: cd .azure && ./deploy.sh
